// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zadanie6.Models;

namespace Zadanie6.Migrations
{
    [DbContext(typeof(StudiesContext))]
    [Migration("20200623132449_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Zadanie6.Models.Enrollment", b =>
                {
                    b.Property<int>("IdEnrollment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdStudy")
                        .HasColumnType("int");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdEnrollment");

                    b.HasIndex("IdStudy");

                    b.ToTable("enrollments");

                    b.HasData(
                        new
                        {
                            IdEnrollment = 1,
                            IdStudy = 1,
                            Semester = 1,
                            StartDate = new DateTime(2020, 6, 23, 15, 24, 49, 327, DateTimeKind.Local).AddTicks(5687)
                        });
                });

            modelBuilder.Entity("Zadanie6.Models.Student", b =>
                {
                    b.Property<string>("IndexNumber")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("IdEnrollment")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("IndexNumber");

                    b.HasIndex("IdEnrollment");

                    b.ToTable("students");

                    b.HasData(
                        new
                        {
                            IndexNumber = "s16859",
                            BirthDate = new DateTime(1995, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Przemyslaw",
                            IdEnrollment = 1,
                            LastName = "Szczerba"
                        });
                });

            modelBuilder.Entity("Zadanie6.Models.Studies", b =>
                {
                    b.Property<int>("IdStudy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("IdStudy");

                    b.ToTable("studies");

                    b.HasData(
                        new
                        {
                            IdStudy = 1,
                            Name = "Jakies"
                        });
                });

            modelBuilder.Entity("Zadanie6.Models.Enrollment", b =>
                {
                    b.HasOne("Zadanie6.Models.Studies", "studies")
                        .WithMany("enrollments")
                        .HasForeignKey("IdStudy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zadanie6.Models.Student", b =>
                {
                    b.HasOne("Zadanie6.Models.Enrollment", "enrollment")
                        .WithMany("students")
                        .HasForeignKey("IdEnrollment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
